[package]
name = "transition"
version = "0.1.0"
authors = ["Alexey Golubev <dr.freecx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lodepng = "3.0"
rgb = "*"